set -qU fish_color_autosuggestion:brblack
set -qU fish_color_cancel:\x2dr
set -qU fish_color_command:blue
set -qU fish_color_comment:red
set -qU fish_color_cwd:green
set -qU fish_color_cwd_root:red
set -qU fish_color_end:green
set -qU fish_color_error:brred
set -qU fish_color_escape:brcyan
set -qU fish_color_history_current:\x2d\x2dbold
set -qU fish_color_host:normal
set -qU fish_color_host_remote:yellow
set -qU fish_color_normal:normal
set -qU fish_color_operator:brcyan
set -qU fish_color_param:cyan
set -qU fish_color_quote:yellow
set -qU fish_color_redirection:cyan\x1e\x2d\x2dbold
set -qU fish_color_search_match:bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -qU fish_color_selection:white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -qU fish_color_status:red
set -qU fish_color_user:brgreen
set -qU fish_color_valid_path:\x2d\x2dunderline
set -qU fish_key_bindings:fish_default_key_bindings
set -qU fish_pager_color_completion:normal
set -qU fish_pager_color_description:yellow\x1e\x2di
set -qU fish_pager_color_prefix:normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -qU fish_pager_color_progress:brwhite\x1e\x2d\x2dbackground\x3dcyan
set -qU fish_pager_color_selected_background:\x2dr
